import type {
  CheckedDocument,
  CreditPack,
  HistoryEntry,
  PlanDefinition,
} from "./types";

export const PLANS: PlanDefinition[] = [
  {
    id: "free",
    name: "Free",
    tagline: "Get started and try a real check",
    priceMonthly: 0,
    priceAnnual: 0,
    audience: "New users, occasional checks",
    features: [
      "3 documents / month, up to 3,000 words each",
      "Traditional plagiarism detection",
      "Similarity score & matched sources",
      "Basic report",
      "7-day history",
      "Ad-supported",
    ],
  },
  {
    id: "student",
    name: "Student Premium",
    tagline: "For students, grad and PhD researchers",
    priceMonthly: 99000,
    priceAnnual: 950000,
    audience: "Students, grad & PhD researchers",
    mostPopular: true,
    features: [
      "Unlimited documents, unlimited words",
      "Semantic plagiarism detection",
      "AI-generated content detection",
      "Explainable AI, in plain language",
      "AI Rewrite Assistant",
      "Multi-language checking",
      "PDF report export",
      "12-month history, no ads",
      "Priority support",
    ],
  },
  {
    id: "professional",
    name: "Professional",
    tagline: "For lecturers, researchers & agencies",
    priceMonthly: 299000,
    priceAnnual: 2870000,
    audience: "Lecturers, researchers, content & SEO teams",
    features: [
      "Everything in Student Premium",
      "Batch checking",
      "Statistics dashboard",
      "Multi-project management",
      "API integration",
      "In-depth advanced report export",
      "Team roles & permissions",
      "24/7 priority support",
    ],
  },
];

export const CREDIT_PACKS: CreditPack[] = [
  { id: "pack1", label: "1 check", checks: 1, price: 19000, perCheck: 19000 },
  {
    id: "pack5",
    label: "5 checks",
    checks: 5,
    price: 89000,
    perCheck: 17800,
    badge: "Save 6%",
  },
  {
    id: "pack10",
    label: "10 checks",
    checks: 10,
    price: 169000,
    perCheck: 16900,
    badge: "Best value",
  },
];

export const COMPETITORS = [
  {
    name: "Turnitin",
    audience: "Universities",
    price: "Not sold directly",
    limitation: "Hard for individuals to access",
  },
  {
    name: "Copyleaks",
    audience: "Individuals",
    price: "~$9.99/mo",
    limitation: "Not optimized for Vietnamese",
  },
  {
    name: "Grammarly Premium",
    audience: "Individuals",
    price: "~$30/mo",
    limitation: "English-focused",
  },
  {
    name: "Quetext Pro",
    audience: "Individuals",
    price: "~$13.99/mo",
    limitation: "Weak Vietnamese semantic detection",
  },
  {
    name: "Etymos",
    audience: "Vietnamese users",
    price: "~99,000 VND/mo (~$3.8)",
    limitation: "Vietnamese-optimized, Explainable AI, AI Rewrite",
    highlight: true,
  },
];

export const FEATURE_MATRIX: {
  feature: string;
  free: boolean | string;
  student: boolean | string;
  professional: boolean | string;
}[] = [
  { feature: "Traditional plagiarism detection", free: true, student: true, professional: true },
  { feature: "Similarity score", free: true, student: true, professional: true },
  { feature: "Matched-source suggestions", free: true, student: true, professional: true },
  { feature: "Semantic plagiarism detection", free: false, student: true, professional: true },
  { feature: "Explainable AI (why it's flagged)", free: false, student: true, professional: true },
  { feature: "AI Rewrite Assistant", free: false, student: true, professional: true },
  { feature: "AI-generated content detection", free: false, student: true, professional: true },
  { feature: "Multi-language checking", free: false, student: true, professional: true },
  { feature: "PDF export", free: false, student: true, professional: true },
  { feature: "Ads", free: "Shown", student: "None", professional: "None" },
  { feature: "Documents / month", free: "3", student: "Unlimited", professional: "Unlimited" },
  { feature: "Words / document", free: "3,000", student: "Unlimited", professional: "Unlimited" },
  { feature: "History retention", free: "7 days", student: "12 months", professional: "12 months" },
  { feature: "Batch checking", free: false, student: false, professional: true },
  { feature: "Statistics dashboard", free: false, student: false, professional: true },
  { feature: "Multi-project management", free: false, student: false, professional: true },
  { feature: "API integration", free: false, student: false, professional: true },
  { feature: "Team roles & permissions", free: false, student: false, professional: true },
  { feature: "Support", free: "Basic", student: "Priority", professional: "24/7 priority" },
];

const title =
  "Tác Động Của Biến Đổi Khí Hậu Đến Sản Xuất Nông Nghiệp Tại Đồng Bằng Sông Cửu Long";

export const SAMPLE_DOCUMENT: CheckedDocument = {
  id: "doc-current",
  title,
  fileName: "Bien-doi-khi-hau-DBSCL.docx",
  language: "vi",
  wordCount: 1842,
  uploadedAt: "2026-07-05",
  similarityScore: 34,
  similarityScoreFree: 22,
  aiContentScore: 62,
  aiContentExplanation:
    "Đoạn văn có khả năng do AI tạo ra dựa trên các dấu hiệu: câu văn trau chuốt và đồng đều bất thường, dùng nhiều cụm từ trừu tượng mang tính khái quát ('kiến tạo tương lai', 'hệ sinh thái bền vững'), và thiếu số liệu cụ thể thường thấy trong văn phong học thuật của người viết.",
  webSourcesScanned: 48200000,
  academicSourcesScanned: 186400,
  passages: [
    {
      id: "p1",
      text: "Đồng bằng sông Cửu Long là vựa lúa lớn nhất của Việt Nam, đóng góp hơn 50% sản lượng lúa gạo và gần 70% sản lượng thủy sản xuất khẩu của cả nước. Tuy nhiên, trong hai thập kỷ gần đây, khu vực này đang phải đối mặt với những thách thức nghiêm trọng từ biến đổi khí hậu, bao gồm xâm nhập mặn, sụt lún đất và nước biển dâng.",
    },
    {
      id: "p2",
      text: "Theo kịch bản biến đổi khí hậu của Bộ Tài nguyên và Môi trường, đến năm 2050, khoảng 38% diện tích của Đồng bằng sông Cửu Long có nguy cơ bị ngập do nước biển dâng nếu không có các biện pháp ứng phó kịp thời. Con số này đặc biệt đáng lo ngại đối với các tỉnh ven biển như Bến Tre, Trà Vinh và Sóc Trăng, nơi sinh kế của hàng triệu nông dân phụ thuộc trực tiếp vào canh tác lúa nước.",
      severity: "high",
      matchId: "m1",
    },
    {
      id: "p3",
      text: "Xâm nhập mặn là một trong những hệ quả rõ rệt nhất của biến đổi khí hậu tại khu vực này. Mùa khô năm 2020, ranh mặn 4g/l đã xâm nhập sâu hơn 50km vào một số cửa sông, khiến hàng chục nghìn hecta lúa bị thiệt hại.",
    },
    {
      id: "p4",
      text: "Nhiều nghiên cứu đã chỉ ra rằng việc khai thác nước ngầm quá mức để phục vụ nuôi trồng thủy sản và sinh hoạt là nguyên nhân chính gây ra hiện tượng sụt lún đất, với tốc độ trung bình từ 1 đến 3 cm mỗi năm tại một số khu vực ven biển, nhanh hơn tốc độ nước biển dâng toàn cầu.",
      severity: "moderate",
      matchId: "m2",
    },
    {
      id: "p5",
      text: "Trước thực trạng đó, nông dân tại nhiều địa phương đã bắt đầu chuyển đổi mô hình canh tác, từ độc canh cây lúa sang mô hình lúa - tôm hoặc luân canh với các loại cây chịu mặn tốt hơn.",
    },
    {
      id: "p6",
      text: "Mô hình lúa - tôm được xem là một giải pháp thích ứng bền vững, giúp nông dân vừa duy trì thu nhập vừa giảm thiểu rủi ro trước tình trạng xâm nhập mặn ngày càng gia tăng.",
      severity: "low",
      matchId: "m3",
    },
    {
      id: "p7",
      text: "Việc ứng dụng công nghệ số trong nông nghiệp thông minh không chỉ tối ưu hóa quy trình canh tác mà còn tạo ra một hệ sinh thái bền vững, nơi dữ liệu và tự động hóa hòa quyện với tri thức bản địa để kiến tạo tương lai nông nghiệp xanh cho toàn vùng.",
      aiFlag: true,
    },
    {
      id: "p8",
      text: "Bên cạnh các giải pháp canh tác, chính quyền địa phương cũng đã đầu tư xây dựng hệ thống cống ngăn mặn tại các cửa sông lớn nhằm kiểm soát nguồn nước ngọt phục vụ sản xuất trong mùa khô.",
    },
    {
      id: "p9",
      text: "Dự án Cống Cái Lớn - Cái Bé, một trong những công trình thủy lợi lớn nhất khu vực, được kỳ vọng sẽ kiểm soát nguồn nước cho khoảng 384.000 hecta đất sản xuất nông nghiệp và nuôi trồng thủy sản tại các tỉnh Kiên Giang, Hậu Giang, Bạc Liêu và một phần Sóc Trăng.",
      severity: "high",
      matchId: "m4",
    },
    {
      id: "p10",
      text: "Nhìn chung, việc ứng phó với biến đổi khí hậu tại Đồng bằng sông Cửu Long đòi hỏi một chiến lược tổng thể, kết hợp giữa giải pháp công trình, chuyển đổi mô hình canh tác và sự tham gia chủ động của cộng đồng địa phương.",
    },
  ],
  matches: [
    {
      id: "m1",
      severity: "high",
      detectionType: "traditional",
      matchPercent: 92,
      sourceTitle: "Kịch bản biến đổi khí hậu và nước biển dâng cho Việt Nam",
      sourceAuthor: "Bộ Tài nguyên và Môi trường, 2022",
      sourceKind: "academic",
      citation: "Bộ TN&MT, 2022, tr. 47",
      userSnippet:
        "Theo kịch bản biến đổi khí hậu của Bộ Tài nguyên và Môi trường, đến năm 2050, khoảng 38% diện tích của Đồng bằng sông Cửu Long có nguy cơ bị ngập do nước biển dâng nếu không có các biện pháp ứng phó kịp thời.",
      sourceSnippet:
        "Theo kịch bản biến đổi khí hậu của Bộ Tài nguyên và Môi trường, đến năm 2050, gần 38% diện tích Đồng bằng sông Cửu Long có nguy cơ ngập do nước biển dâng nếu Việt Nam không triển khai kịp thời các biện pháp ứng phó.",
      explanation:
        "Câu văn giữ gần như nguyên vẹn cấu trúc và số liệu của nguồn gốc, chỉ thay đổi vài từ nối. Đây là dạng sao chép gần nguyên văn (near-verbatim), không phải diễn giải lại bằng ngôn ngữ của người viết.",
      rewriteSuggestions: [
        "Dựa trên kịch bản biến đổi khí hậu do Bộ Tài nguyên và Môi trường công bố, gần 38% diện tích Đồng bằng sông Cửu Long được dự báo sẽ chịu ảnh hưởng của ngập lụt do nước biển dâng vào năm 2050 nếu thiếu các giải pháp ứng phó phù hợp. Các tỉnh ven biển như Bến Tre, Trà Vinh và Sóc Trăng là những khu vực chịu rủi ro cao nhất, do phần lớn dân cư nơi đây sống dựa vào canh tác lúa nước.",
        "Số liệu dự báo của Bộ Tài nguyên và Môi trường cho thấy, nếu không triển khai các giải pháp ứng phó phù hợp, gần 2/5 diện tích Đồng bằng sông Cửu Long có thể bị ảnh hưởng bởi ngập lụt do nước biển dâng vào giữa thế kỷ. Rủi ro này đặc biệt cao tại các tỉnh ven biển như Bến Tre, Trà Vinh và Sóc Trăng, nơi phần lớn sinh kế người dân gắn với cây lúa.",
      ],
    },
    {
      id: "m2",
      severity: "moderate",
      detectionType: "semantic",
      matchPercent: 61,
      sourceTitle: "Sụt lún đất ở Đồng bằng sông Cửu Long: Nguyên nhân và giải pháp",
      sourceAuthor: "Nguyễn Hồng Quân và cộng sự, Tạp chí Khoa học Thủy lợi",
      sourceKind: "academic",
      citation: "Nguyễn H. Quân và cộng sự, 2021, tr. 12",
      userSnippet:
        "Nhiều nghiên cứu đã chỉ ra rằng việc khai thác nước ngầm quá mức để phục vụ nuôi trồng thủy sản và sinh hoạt là nguyên nhân chính gây ra hiện tượng sụt lún đất, với tốc độ trung bình từ 1 đến 3 cm mỗi năm.",
      sourceSnippet:
        "Kết quả quan trắc cho thấy khai thác nước ngầm quá mức phục vụ nuôi trồng thủy sản và sinh hoạt là nguyên nhân chủ yếu dẫn đến sụt lún đất, với tốc độ trung bình 1-3 cm/năm ở một số khu vực ven biển.",
      explanation:
        "Đoạn văn diễn đạt lại câu chữ nhưng giữ nguyên toàn bộ lập luận, số liệu và trình tự lý giải nguyên nhân - kết quả của nguồn. Đây là dạng đạo văn ngữ nghĩa (paraphrase), khó phát hiện bằng công cụ so khớp từ khóa thông thường.",
      rewriteSuggestions: [
        "Việc khai thác nước ngầm vượt mức cho phép, phục vụ nuôi trồng thủy sản và sinh hoạt hàng ngày, được xác định là nguyên nhân hàng đầu gây sụt lún đất tại một số khu vực ven biển, với tốc độ trung bình 1 đến 3 cm mỗi năm, vượt xa tốc độ dâng lên của mực nước biển trên phạm vi toàn cầu.",
        "Tại nhiều khu vực ven biển, tình trạng sụt lún đất diễn ra với tốc độ trung bình 1 đến 3 cm mỗi năm, nhanh hơn đáng kể so với tốc độ nước biển dâng toàn cầu. Nguyên nhân chủ yếu được cho là do khai thác nước ngầm quá mức phục vụ sinh hoạt và nuôi trồng thủy sản.",
      ],
    },
    {
      id: "m3",
      severity: "low",
      detectionType: "traditional",
      matchPercent: 34,
      sourceTitle: "Chuyển đổi mô hình lúa - tôm thích ứng biến đổi khí hậu",
      sourceAuthor: "Cổng thông tin Nông nghiệp Việt Nam",
      sourceKind: "web",
      citation: "nongnghiep.vn, truy cập 2026",
      userSnippet:
        "Mô hình lúa - tôm được xem là một giải pháp thích ứng bền vững, giúp nông dân vừa duy trì thu nhập vừa giảm thiểu rủi ro trước tình trạng xâm nhập mặn ngày càng gia tăng.",
      sourceSnippet:
        "Mô hình lúa - tôm được đánh giá là giải pháp thích ứng bền vững, giúp nông dân duy trì thu nhập ổn định trong khi giảm thiểu rủi ro do xâm nhập mặn.",
      explanation:
        "Đây chủ yếu là cách diễn đạt phổ biến, lặp lại trong nhiều bài viết cùng chủ đề. Mức độ trùng khớp thấp và không bắt buộc trích dẫn, nhưng nên diễn đạt theo văn phong riêng để đảm bảo tính nguyên bản.",
      rewriteSuggestions: [
        "Chuyển sang mô hình canh tác lúa kết hợp nuôi tôm giúp nông dân giữ được nguồn thu nhập ổn định, đồng thời hạn chế rủi ro từ tình trạng xâm nhập mặn ngày càng diễn biến phức tạp.",
        "Đây được xem là hướng canh tác thích ứng hiệu quả, cho phép nông dân duy trì thu nhập trong khi giảm bớt tác động tiêu cực của xâm nhập mặn.",
      ],
    },
    {
      id: "m4",
      severity: "high",
      detectionType: "traditional",
      matchPercent: 88,
      sourceTitle: "Báo cáo tổng kết Dự án Hệ thống thủy lợi Cái Lớn - Cái Bé",
      sourceAuthor: "Bộ Nông nghiệp và Phát triển Nông thôn",
      sourceKind: "academic",
      citation: "Bộ NN&PTNT, 2023, tr. 5",
      userSnippet:
        "Dự án Cống Cái Lớn - Cái Bé, một trong những công trình thủy lợi lớn nhất khu vực, được kỳ vọng sẽ kiểm soát nguồn nước cho khoảng 384.000 hecta đất sản xuất nông nghiệp và nuôi trồng thủy sản.",
      sourceSnippet:
        "Hệ thống công trình thủy lợi Cái Lớn - Cái Bé được kỳ vọng kiểm soát nguồn nước cho 384.000 ha đất sản xuất nông nghiệp, nuôi trồng thủy sản thuộc các tỉnh Kiên Giang, Hậu Giang, Bạc Liêu và một phần tỉnh Sóc Trăng.",
      explanation:
        "Số liệu diện tích, tên dự án và danh sách địa phương được sao chép gần như chính xác từ báo cáo gốc mà không có trích dẫn nguồn. Cần bổ sung trích dẫn trực tiếp hoặc diễn đạt lại toàn bộ câu bằng văn phong riêng.",
      rewriteSuggestions: [
        "Theo báo cáo của Bộ Nông nghiệp và Phát triển Nông thôn (2023), hệ thống cống Cái Lớn - Cái Bé hướng đến mục tiêu kiểm soát nguồn nước cho gần 384.000 hecta đất nông nghiệp và nuôi trồng thủy sản trải rộng trên địa bàn các tỉnh Kiên Giang, Hậu Giang, Bạc Liêu và một phần Sóc Trăng.",
        "Công trình cống Cái Lớn - Cái Bé, theo số liệu công bố năm 2023, dự kiến phục vụ kiểm soát nguồn nước cho khoảng 384.000 hecta đất sản xuất nông nghiệp và thủy sản tại bốn tỉnh Kiên Giang, Hậu Giang, Bạc Liêu và một phần Sóc Trăng.",
      ],
    },
  ],
};

function buildMatch(
  id: string,
  severity: "high" | "moderate" | "low",
  detectionType: "traditional" | "semantic",
  matchPercent: number,
  sourceTitle: string,
  sourceAuthor: string,
  sourceKind: "web" | "academic",
  citation: string,
  userSnippet: string,
  sourceSnippet: string,
  explanation: string,
  rewriteSuggestions: string[],
): CheckedDocument["matches"][number] {
  return {
    id,
    severity,
    detectionType,
    matchPercent,
    sourceTitle,
    sourceAuthor,
    sourceKind,
    citation,
    userSnippet,
    sourceSnippet,
    explanation,
    rewriteSuggestions,
  };
}

export const MOCK_DOCUMENTS: CheckedDocument[] = [
  SAMPLE_DOCUMENT,
  {
    id: "mock-2",
    title: "Ứng Dụng Trí Tuệ Nhân Tạo Trong Đổi Mới Phương Pháp Giáo Dục",
    fileName: "AI-trong-giao-duc.docx",
    language: "vi",
    wordCount: 1560,
    uploadedAt: "2026-06-30",
    similarityScore: 21,
    similarityScoreFree: 14,
    aiContentScore: 38,
    aiContentExplanation:
      "Một số đoạn có cấu trúc câu đồng đều và thiếu ví dụ cụ thể, gợi ý khả năng hỗ trợ từ công cụ AI trong giai đoạn viết nháp.",
    webSourcesScanned: 31500000,
    academicSourcesScanned: 92100,
    passages: [
      { id: "p1", text: "Trí tuệ nhân tạo (AI) đang dần trở thành công cụ hỗ trợ đắc lực trong giáo dục, từ cá nhân hóa lộ trình học tập đến tự động chấm điểm bài luận." },
      { id: "p2", text: "Các nền tảng học tập thích ứng sử dụng thuật toán học máy để phân tích tốc độ tiếp thu của từng học sinh và điều chỉnh độ khó bài tập theo thời gian thực.", severity: "moderate", matchId: "m1" },
      { id: "p3", text: "Việc tích hợp trợ lý ảo trong lớp học giúp giáo viên tiết kiệm thời gian soạn giáo án, đồng thời tạo ra một hệ sinh thái học tập thông minh, kết nối liền mạch giữa dữ liệu và trải nghiệm cá nhân hóa.", aiFlag: true },
      { id: "p4", text: "Tuy nhiên, việc phụ thuộc quá mức vào AI cũng đặt ra thách thức về tính công bằng trong tiếp cận công nghệ giữa các vùng miền.", severity: "low", matchId: "m2" },
    ],
    matches: [
      buildMatch(
        "m1", "moderate", "semantic", 58,
        "Học tập thích ứng và vai trò của AI trong lớp học hiện đại",
        "Phạm Thùy Linh, Tạp chí Giáo dục", "academic", "Phạm T. Linh, 2022, tr. 22",
        "Các nền tảng học tập thích ứng sử dụng thuật toán học máy để phân tích tốc độ tiếp thu của từng học sinh và điều chỉnh độ khó bài tập theo thời gian thực.",
        "Nền tảng học tập thích ứng dùng thuật toán học máy nhằm phân tích tốc độ tiếp thu của người học, từ đó điều chỉnh độ khó bài tập theo thời gian thực.",
        "Câu văn diễn đạt lại nhưng giữ nguyên lập luận và trình tự ý tưởng của nguồn, không phải phân tích độc lập.",
        ["Bằng cách phân tích tốc độ tiếp thu của người học theo thời gian thực, các nền tảng học tập thích ứng có thể tự động điều chỉnh độ khó của bài tập cho phù hợp với từng cá nhân."],
      ),
      buildMatch(
        "m2", "low", "traditional", 29,
        "Khoảng cách số trong giáo dục vùng sâu vùng xa",
        "Cổng thông tin Giáo dục & Thời đại", "web", "giaoducthoidai.vn, truy cập 2026",
        "Việc phụ thuộc quá mức vào AI cũng đặt ra thách thức về tính công bằng trong tiếp cận công nghệ giữa các vùng miền.",
        "Phụ thuộc vào công nghệ AI trong giáo dục có thể làm gia tăng bất bình đẳng tiếp cận giữa các vùng miền khác nhau.",
        "Ý tưởng phổ biến, mức trùng khớp thấp, nhưng nên diễn đạt lại theo văn phong riêng.",
        ["Sự phụ thuộc ngày càng lớn vào AI trong giáo dục có nguy cơ khoét sâu thêm khoảng cách tiếp cận công nghệ giữa các vùng miền."],
      ),
    ],
  },
  {
    id: "mock-3",
    title: "Chuyển Đổi Số Trong Doanh Nghiệp Vừa Và Nhỏ Tại Việt Nam",
    fileName: "Chuyen-doi-so-SME.pdf",
    language: "vi",
    wordCount: 2140,
    uploadedAt: "2026-06-22",
    similarityScore: 45,
    similarityScoreFree: 30,
    aiContentScore: 12,
    aiContentExplanation: "Văn phong tự nhiên, có số liệu và ví dụ cụ thể, ít dấu hiệu do AI tạo ra.",
    webSourcesScanned: 40200000,
    academicSourcesScanned: 74300,
    passages: [
      { id: "p1", text: "Chuyển đổi số đang trở thành yêu cầu sống còn đối với các doanh nghiệp vừa và nhỏ (SME) tại Việt Nam trong bối cảnh cạnh tranh ngày càng gay gắt." },
      { id: "p2", text: "Theo khảo sát năm 2023, chỉ khoảng 31% doanh nghiệp SME đã triển khai đầy đủ các giải pháp quản trị số, phần còn lại vẫn phụ thuộc vào quy trình thủ công.", severity: "high", matchId: "m1" },
      { id: "p3", text: "Rào cản lớn nhất được ghi nhận là chi phí đầu tư ban đầu và thiếu nhân lực có kỹ năng công nghệ phù hợp.", severity: "moderate", matchId: "m2" },
      { id: "p4", text: "Chính phủ đã triển khai nhiều chương trình hỗ trợ tài chính và đào tạo nhằm thúc đẩy quá trình này diễn ra nhanh hơn." },
    ],
    matches: [
      buildMatch(
        "m1", "high", "traditional", 84,
        "Báo cáo Chỉ số chuyển đổi số doanh nghiệp Việt Nam 2023",
        "Bộ Kế hoạch và Đầu tư", "academic", "Bộ KH&ĐT, 2023, tr. 9",
        "Theo khảo sát năm 2023, chỉ khoảng 31% doanh nghiệp SME đã triển khai đầy đủ các giải pháp quản trị số, phần còn lại vẫn phụ thuộc vào quy trình thủ công.",
        "Kết quả khảo sát năm 2023 cho thấy chỉ 31% doanh nghiệp nhỏ và vừa triển khai đầy đủ giải pháp quản trị số, số còn lại vẫn dựa vào quy trình thủ công.",
        "Số liệu và cấu trúc câu gần như sao chép nguyên văn từ báo cáo gốc, cần trích dẫn trực tiếp hoặc diễn đạt lại.",
        ["Số liệu khảo sát năm 2023 của Bộ Kế hoạch và Đầu tư cho thấy chỉ khoảng 31% doanh nghiệp vừa và nhỏ đã ứng dụng đầy đủ các giải pháp quản trị số, trong khi phần lớn vẫn vận hành theo phương thức thủ công."],
      ),
      buildMatch(
        "m2", "moderate", "semantic", 55,
        "Rào cản chuyển đổi số ở khu vực doanh nghiệp tư nhân",
        "Nguyễn Đức Anh, Tạp chí Kinh tế và Dự báo", "academic", "Nguyễn Đ. Anh, 2022, tr. 15",
        "Rào cản lớn nhất được ghi nhận là chi phí đầu tư ban đầu và thiếu nhân lực có kỹ năng công nghệ phù hợp.",
        "Nghiên cứu chỉ ra hai rào cản chính là chi phí đầu tư ban đầu cao và sự thiếu hụt nhân lực có kỹ năng công nghệ.",
        "Diễn đạt lại nhưng giữ nguyên hai luận điểm chính theo đúng thứ tự của nguồn.",
        ["Hai rào cản được nhắc đến nhiều nhất là mức chi phí đầu tư ban đầu còn cao và tình trạng thiếu hụt nhân lực có kỹ năng công nghệ phù hợp."],
      ),
    ],
  },
  {
    id: "mock-4",
    title: "Ô Nhiễm Vi Nhựa Trong Nguồn Nước Ngọt Tại Việt Nam",
    fileName: "O-nhiem-vi-nhua.docx",
    language: "vi",
    wordCount: 1780,
    uploadedAt: "2026-06-18",
    similarityScore: 8,
    similarityScoreFree: 5,
    aiContentScore: 6,
    aiContentExplanation: "Không phát hiện dấu hiệu rõ ràng của nội dung do AI tạo ra.",
    webSourcesScanned: 27800000,
    academicSourcesScanned: 61200,
    passages: [
      { id: "p1", text: "Vi nhựa, những mảnh nhựa có kích thước nhỏ hơn 5mm, đang ngày càng xuất hiện phổ biến trong các nguồn nước ngọt tại Việt Nam." },
      { id: "p2", text: "Nghiên cứu tại lưu vực sông Sài Gòn - Đồng Nai ghi nhận nồng độ vi nhựa trung bình cao hơn nhiều so với các con sông ở khu vực Đông Nam Á khác.", severity: "low", matchId: "m1" },
      { id: "p3", text: "Nguồn phát thải chủ yếu đến từ rác thải sinh hoạt, nước thải công nghiệp dệt may và hoạt động đánh bắt thủy sản." },
      { id: "p4", text: "Các chuyên gia khuyến nghị cần có quy định chặt chẽ hơn về xử lý nước thải trước khi xả ra môi trường tự nhiên." },
    ],
    matches: [
      buildMatch(
        "m1", "low", "traditional", 33,
        "Khảo sát vi nhựa trong hệ thống sông ngòi Đông Nam Á",
        "Viện Môi trường và Tài nguyên", "academic", "Viện MT&TN, 2023, tr. 41",
        "Nghiên cứu tại lưu vực sông Sài Gòn - Đồng Nai ghi nhận nồng độ vi nhựa trung bình cao hơn nhiều so với các con sông ở khu vực Đông Nam Á khác.",
        "Khảo sát lưu vực sông Sài Gòn - Đồng Nai cho thấy nồng độ vi nhựa cao hơn đáng kể so với nhiều con sông khác trong khu vực Đông Nam Á.",
        "Diễn đạt gần giống, mức trùng khớp thấp nhưng nên nêu rõ nguồn trích dẫn.",
        ["Kết quả khảo sát cho thấy lưu vực sông Sài Gòn - Đồng Nai có nồng độ vi nhựa cao hơn đáng kể so với nhiều con sông khác trong khu vực."],
      ),
    ],
  },
  {
    id: "mock-5",
    title: "Tác Động Của Mạng Xã Hội Đến Sức Khỏe Tâm Thần Thanh Thiếu Niên",
    fileName: "Mang-xa-hoi-suc-khoe-tam-than.docx",
    language: "vi",
    wordCount: 1920,
    uploadedAt: "2026-06-10",
    similarityScore: 52,
    similarityScoreFree: 37,
    aiContentScore: 71,
    aiContentExplanation:
      "Đoạn văn có xu hướng liệt kê khái quát, thiếu trích dẫn nghiên cứu cụ thể và dùng nhiều cụm từ mang tính tổng hợp, đặc trưng của văn bản do AI hỗ trợ soạn thảo.",
    webSourcesScanned: 55600000,
    academicSourcesScanned: 118400,
    passages: [
      { id: "p1", text: "Mạng xã hội đã trở thành một phần không thể thiếu trong đời sống của thanh thiếu niên, nhưng đi kèm với đó là những lo ngại ngày càng tăng về sức khỏe tâm thần." },
      { id: "p2", text: "Việc so sánh bản thân với hình ảnh được chỉnh sửa hoàn hảo trên mạng xã hội có liên quan mật thiết đến gia tăng tỷ lệ lo âu và trầm cảm ở tuổi vị thành niên.", severity: "high", matchId: "m1" },
      { id: "p3", text: "Song song đó, việc xây dựng một hệ sinh thái số lành mạnh, kết hợp giáo dục kỹ năng số và sự đồng hành của gia đình, được xem là chìa khóa kiến tạo tương lai bền vững cho thế hệ trẻ.", aiFlag: true },
      { id: "p4", text: "Nhiều chuyên gia khuyến nghị giới hạn thời gian sử dụng thiết bị và khuyến khích các hoạt động ngoài trời.", severity: "low", matchId: "m2" },
    ],
    matches: [
      buildMatch(
        "m1", "high", "semantic", 90,
        "Mạng xã hội, hình ảnh bản thân và sức khỏe tâm lý vị thành niên",
        "Trần Bảo Ngọc, Tạp chí Tâm lý học", "academic", "Trần B. Ngọc, 2022, tr. 33",
        "Việc so sánh bản thân với hình ảnh được chỉnh sửa hoàn hảo trên mạng xã hội có liên quan mật thiết đến gia tăng tỷ lệ lo âu và trầm cảm ở tuổi vị thành niên.",
        "Xu hướng so sánh bản thân với các hình ảnh đã qua chỉnh sửa trên mạng xã hội có mối liên hệ chặt chẽ với sự gia tăng lo âu và trầm cảm ở lứa tuổi vị thành niên.",
        "Giữ nguyên lập luận nhân quả và gần như toàn bộ cấu trúc câu của nguồn, chỉ thay đổi một vài từ.",
        ["Nghiên cứu cho thấy việc thường xuyên so sánh bản thân với những hình ảnh đã được chỉnh sửa trên mạng xã hội có liên hệ chặt chẽ với tỷ lệ lo âu và trầm cảm gia tăng ở tuổi vị thành niên."],
      ),
      buildMatch(
        "m2", "low", "traditional", 24,
        "Hướng dẫn sử dụng thiết bị điện tử lành mạnh cho trẻ vị thành niên",
        "Bộ Y tế", "web", "moh.gov.vn, truy cập 2026",
        "Nhiều chuyên gia khuyến nghị giới hạn thời gian sử dụng thiết bị và khuyến khích các hoạt động ngoài trời.",
        "Các chuyên gia khuyến cáo nên giới hạn thời gian dùng thiết bị điện tử và tăng cường hoạt động ngoài trời cho trẻ.",
        "Khuyến nghị phổ biến, mức trùng khớp thấp, nên diễn đạt theo văn phong riêng.",
        ["Giới hạn thời gian tiếp xúc với thiết bị điện tử và khuyến khích tham gia hoạt động ngoài trời là khuyến nghị được nhiều chuyên gia đồng thuận."],
      ),
    ],
  },
  {
    id: "mock-6",
    title: "Ứng Dụng Blockchain Trong Truy Xuất Nguồn Gốc Nông Sản",
    fileName: "Blockchain-nong-san.pdf",
    language: "vi",
    wordCount: 2050,
    uploadedAt: "2026-06-05",
    similarityScore: 17,
    similarityScoreFree: 11,
    aiContentScore: 9,
    aiContentExplanation: "Văn bản có ví dụ thực tế và số liệu chi tiết, ít khả năng do AI tạo ra.",
    webSourcesScanned: 33100000,
    academicSourcesScanned: 68900,
    passages: [
      { id: "p1", text: "Công nghệ blockchain cho phép ghi nhận toàn bộ hành trình của một sản phẩm nông sản, từ khâu gieo trồng đến khi đến tay người tiêu dùng." },
      { id: "p2", text: "Một số hợp tác xã tại Đồng Tháp đã thử nghiệm gắn mã QR liên kết blockchain cho sản phẩm xoài xuất khẩu, giúp tăng giá bán trung bình 12%.", severity: "moderate", matchId: "m1" },
      { id: "p3", text: "Thách thức chính nằm ở chi phí triển khai hạ tầng và việc đào tạo nông dân sử dụng công nghệ mới." },
      { id: "p4", text: "Về dài hạn, đây được xem là hướng đi cần thiết để nông sản Việt Nam đáp ứng các tiêu chuẩn truy xuất nguồn gốc ngày càng khắt khe của thị trường quốc tế." },
    ],
    matches: [
      buildMatch(
        "m1", "moderate", "traditional", 63,
        "Blockchain trong nông nghiệp: Trường hợp thí điểm tại Đồng Tháp",
        "Sở Nông nghiệp và Phát triển Nông thôn Đồng Tháp", "web", "dongthap.gov.vn, truy cập 2026",
        "Một số hợp tác xã tại Đồng Tháp đã thử nghiệm gắn mã QR liên kết blockchain cho sản phẩm xoài xuất khẩu, giúp tăng giá bán trung bình 12%.",
        "Thí điểm gắn mã QR blockchain cho xoài xuất khẩu tại một số hợp tác xã Đồng Tháp đã giúp giá bán trung bình tăng khoảng 12%.",
        "Số liệu và bối cảnh cụ thể trùng khớp cao với nguồn, nên trích dẫn trực tiếp.",
        ["Theo thông tin từ Sở Nông nghiệp và Phát triển Nông thôn Đồng Tháp, việc thí điểm gắn mã QR liên kết blockchain cho xoài xuất khẩu đã giúp một số hợp tác xã tăng giá bán trung bình khoảng 12%."],
      ),
    ],
  },
  {
    id: "mock-7",
    title: "Năng Lượng Tái Tạo Và Bài Toán An Ninh Năng Lượng Việt Nam",
    fileName: "Nang-luong-tai-tao.docx",
    language: "vi",
    wordCount: 2280,
    uploadedAt: "2026-05-28",
    similarityScore: 39,
    similarityScoreFree: 26,
    aiContentScore: 15,
    aiContentExplanation: "Cấu trúc lập luận tự nhiên với số liệu cụ thể, ít dấu hiệu AI.",
    webSourcesScanned: 46700000,
    academicSourcesScanned: 103200,
    passages: [
      { id: "p1", text: "Việt Nam đặt mục tiêu đạt phát thải ròng bằng 0 vào năm 2050, trong đó năng lượng tái tạo đóng vai trò trung tâm trong chiến lược chuyển dịch năng lượng." },
      { id: "p2", text: "Tính đến năm 2023, điện mặt trời và điện gió đã chiếm khoảng 27% tổng công suất lắp đặt của hệ thống điện quốc gia.", severity: "high", matchId: "m1" },
      { id: "p3", text: "Tuy nhiên, tình trạng quá tải lưới điện tại một số khu vực miền Trung và miền Nam đang cản trở việc giải phóng hết công suất của các nhà máy năng lượng tái tạo.", severity: "moderate", matchId: "m2" },
      { id: "p4", text: "Đầu tư vào hệ thống lưu trữ năng lượng và nâng cấp lưới truyền tải được xem là điều kiện tiên quyết để giải quyết vấn đề này." },
    ],
    matches: [
      buildMatch(
        "m1", "high", "traditional", 87,
        "Báo cáo hiện trạng hệ thống điện Việt Nam 2023",
        "Bộ Công Thương", "academic", "Bộ Công Thương, 2023, tr. 18",
        "Tính đến năm 2023, điện mặt trời và điện gió đã chiếm khoảng 27% tổng công suất lắp đặt của hệ thống điện quốc gia.",
        "Theo số liệu năm 2023, điện mặt trời và điện gió chiếm gần 27% tổng công suất lắp đặt của toàn hệ thống điện quốc gia.",
        "Số liệu và câu văn gần như trùng khớp hoàn toàn với báo cáo gốc, cần trích dẫn rõ ràng.",
        ["Số liệu công bố năm 2023 cho thấy điện mặt trời và điện gió đã đóng góp gần 27% tổng công suất lắp đặt của hệ thống điện quốc gia."],
      ),
      buildMatch(
        "m2", "moderate", "semantic", 52,
        "Quá tải lưới điện: Nút thắt của năng lượng tái tạo miền Trung",
        "Đỗ Văn Hùng, Tạp chí Năng lượng Việt Nam", "web", "nangluongvietnam.vn, truy cập 2026",
        "Tình trạng quá tải lưới điện tại một số khu vực miền Trung và miền Nam đang cản trở việc giải phóng hết công suất của các nhà máy năng lượng tái tạo.",
        "Quá tải lưới điện ở một số tỉnh miền Trung, miền Nam khiến các nhà máy năng lượng tái tạo không thể giải phóng hết công suất.",
        "Diễn đạt lại nhưng giữ nguyên luận điểm và mối quan hệ nhân quả của nguồn.",
        ["Ở một số khu vực miền Trung và miền Nam, tình trạng quá tải lưới điện đang khiến các nhà máy năng lượng tái tạo chưa thể vận hành hết công suất."],
      ),
    ],
  },
  {
    id: "mock-8",
    title: "Du Lịch Bền Vững Tại Các Tỉnh Duyên Hải Miền Trung",
    fileName: "Du-lich-ben-vung-mien-trung.docx",
    language: "vi",
    wordCount: 1680,
    uploadedAt: "2026-05-20",
    similarityScore: 6,
    similarityScoreFree: 4,
    aiContentScore: 5,
    aiContentExplanation: "Không phát hiện dấu hiệu rõ ràng của nội dung do AI tạo ra.",
    webSourcesScanned: 29400000,
    academicSourcesScanned: 55700,
    passages: [
      { id: "p1", text: "Du lịch bền vững đang được xem là hướng phát triển ưu tiên tại các tỉnh duyên hải miền Trung nhằm cân bằng giữa tăng trưởng kinh tế và bảo tồn tài nguyên tự nhiên." },
      { id: "p2", text: "Mô hình du lịch cộng đồng tại một số làng chài đã giúp tăng thu nhập cho người dân địa phương mà không gây áp lực lớn lên hệ sinh thái ven biển.", severity: "low", matchId: "m1" },
      { id: "p3", text: "Việc kiểm soát số lượng khách tham quan tại các khu vực nhạy cảm về sinh thái vẫn còn nhiều hạn chế." },
      { id: "p4", text: "Hợp tác giữa chính quyền địa phương và doanh nghiệp lữ hành được kỳ vọng sẽ cải thiện tình hình trong giai đoạn tới." },
    ],
    matches: [
      buildMatch(
        "m1", "low", "traditional", 31,
        "Mô hình du lịch cộng đồng ven biển miền Trung",
        "Tổng cục Du lịch", "web", "vietnamtourism.gov.vn, truy cập 2026",
        "Mô hình du lịch cộng đồng tại một số làng chài đã giúp tăng thu nhập cho người dân địa phương mà không gây áp lực lớn lên hệ sinh thái ven biển.",
        "Du lịch cộng đồng tại các làng chài ven biển đã góp phần tăng thu nhập người dân mà không tạo áp lực lớn lên môi trường sinh thái.",
        "Diễn đạt gần giống, mức trùng khớp thấp, nên nêu rõ nguồn.",
        ["Tại một số làng chài, mô hình du lịch cộng đồng đã giúp cải thiện thu nhập người dân địa phương mà không gây áp lực đáng kể lên hệ sinh thái ven biển."],
      ),
    ],
  },
  {
    id: "mock-9",
    title: "Thương Mại Điện Tử Xuyên Biên Giới Của Doanh Nghiệp Việt Nam",
    fileName: "TMDT-xuyen-bien-gioi.pdf",
    language: "vi",
    wordCount: 1990,
    uploadedAt: "2026-05-14",
    similarityScore: 28,
    similarityScoreFree: 19,
    aiContentScore: 44,
    aiContentExplanation:
      "Một số đoạn dùng cụm từ khái quát và liệt kê lợi ích chung chung, có khả năng được hỗ trợ soạn thảo bởi AI.",
    webSourcesScanned: 38900000,
    academicSourcesScanned: 71600,
    passages: [
      { id: "p1", text: "Thương mại điện tử xuyên biên giới đang mở ra cơ hội lớn cho doanh nghiệp Việt Nam tiếp cận thị trường quốc tế mà không cần đầu tư hạ tầng phân phối vật lý." },
      { id: "p2", text: "Theo thống kê, doanh thu thương mại điện tử xuyên biên giới của Việt Nam đã tăng trưởng trung bình 20% mỗi năm trong giai đoạn 2020-2023.", severity: "moderate", matchId: "m1" },
      { id: "p3", text: "Việc xây dựng thương hiệu số mạnh mẽ, kết hợp tối ưu hóa trải nghiệm khách hàng đa kênh, được xem là chìa khóa kiến tạo lợi thế cạnh tranh bền vững trên thị trường toàn cầu.", aiFlag: true },
      { id: "p4", text: "Rào cản về logistics quốc tế và thủ tục hải quan vẫn là thách thức lớn đối với nhiều doanh nghiệp vừa và nhỏ." },
    ],
    matches: [
      buildMatch(
        "m1", "moderate", "traditional", 60,
        "Báo cáo Thương mại điện tử Việt Nam 2023",
        "Cục Thương mại điện tử và Kinh tế số", "academic", "Cục TMĐT & KTS, 2023, tr. 27",
        "Theo thống kê, doanh thu thương mại điện tử xuyên biên giới của Việt Nam đã tăng trưởng trung bình 20% mỗi năm trong giai đoạn 2020-2023.",
        "Số liệu thống kê cho thấy doanh thu thương mại điện tử xuyên biên giới của Việt Nam tăng trưởng bình quân 20%/năm trong giai đoạn 2020-2023.",
        "Số liệu và giai đoạn thời gian trùng khớp gần như hoàn toàn với nguồn, cần trích dẫn cụ thể.",
        ["Theo báo cáo của Cục Thương mại điện tử và Kinh tế số, doanh thu thương mại điện tử xuyên biên giới của Việt Nam đã tăng trưởng bình quân khoảng 20% mỗi năm trong giai đoạn 2020-2023."],
      ),
    ],
  },
  {
    id: "mock-10",
    title: "An Ninh Mạng Trong Hệ Thống Ngân Hàng Số Tại Việt Nam",
    fileName: "An-ninh-mang-ngan-hang-so.docx",
    language: "vi",
    wordCount: 2170,
    uploadedAt: "2026-05-08",
    similarityScore: 61,
    similarityScoreFree: 43,
    aiContentScore: 19,
    aiContentExplanation: "Văn phong kỹ thuật cụ thể, ít dấu hiệu do AI tạo ra.",
    webSourcesScanned: 42300000,
    academicSourcesScanned: 89500,
    passages: [
      { id: "p1", text: "Chuyển đổi số trong ngành ngân hàng đã kéo theo sự gia tăng đáng kể về nguy cơ tấn công mạng nhắm vào hệ thống giao dịch trực tuyến." },
      { id: "p2", text: "Trong năm 2023, các ngân hàng Việt Nam ghi nhận hơn 12.000 sự cố an ninh mạng liên quan đến giao dịch số, tăng 35% so với năm trước.", severity: "high", matchId: "m1" },
      { id: "p3", text: "Xác thực đa yếu tố và giám sát hành vi bất thường theo thời gian thực là hai giải pháp được nhiều ngân hàng ưu tiên triển khai.", severity: "low", matchId: "m2" },
      { id: "p4", text: "Ngân hàng Nhà nước cũng đã ban hành các quy định nghiêm ngặt hơn về bảo mật dữ liệu khách hàng." },
    ],
    matches: [
      buildMatch(
        "m1", "high", "traditional", 91,
        "Báo cáo An ninh mạng ngành Ngân hàng 2023",
        "Ngân hàng Nhà nước Việt Nam", "academic", "NHNN, 2023, tr. 6",
        "Trong năm 2023, các ngân hàng Việt Nam ghi nhận hơn 12.000 sự cố an ninh mạng liên quan đến giao dịch số, tăng 35% so với năm trước.",
        "Năm 2023, hệ thống ngân hàng Việt Nam ghi nhận hơn 12.000 sự cố an ninh mạng liên quan đến giao dịch số, tăng 35% so với cùng kỳ năm trước.",
        "Số liệu và cấu trúc câu gần như trùng khớp hoàn toàn với báo cáo gốc.",
        ["Theo báo cáo của Ngân hàng Nhà nước, năm 2023 ghi nhận hơn 12.000 sự cố an ninh mạng liên quan đến giao dịch số trong hệ thống ngân hàng, tăng 35% so với năm trước đó."],
      ),
      buildMatch(
        "m2", "low", "semantic", 38,
        "Giải pháp xác thực đa yếu tố cho ngân hàng số",
        "Lê Quang Huy, Tạp chí Công nghệ Ngân hàng", "academic", "Lê Q. Huy, 2022, tr. 44",
        "Xác thực đa yếu tố và giám sát hành vi bất thường theo thời gian thực là hai giải pháp được nhiều ngân hàng ưu tiên triển khai.",
        "Nhiều ngân hàng ưu tiên triển khai xác thực đa yếu tố kết hợp giám sát hành vi bất thường theo thời gian thực để tăng cường bảo mật.",
        "Diễn đạt lại, giữ nguyên hai giải pháp chính theo đúng thứ tự nguồn.",
        ["Hai giải pháp bảo mật được nhiều ngân hàng ưu tiên là xác thực đa yếu tố và giám sát hành vi bất thường theo thời gian thực."],
      ),
    ],
  },
];

export const HISTORY_SEED: HistoryEntry[] = [
  {
    id: "hist-1",
    title: title,
    date: "2026-07-05",
    similarityScore: 34,
    status: "moderate",
    aiFlagged: true,
    project: "Luận văn tốt nghiệp",
    wordCount: 1842,
  },
  {
    id: "hist-2",
    title: "Ứng Dụng Trí Tuệ Nhân Tạo Trong Chẩn Đoán Hình Ảnh Y Khoa",
    date: "2026-06-28",
    similarityScore: 18,
    status: "low",
    aiFlagged: false,
    project: "Nghiên cứu khoa học",
    wordCount: 2310,
  },
  {
    id: "hist-3",
    title: "Tác Động Của Mạng Xã Hội Đến Hành Vi Tiêu Dùng Của Sinh Viên",
    date: "2026-06-20",
    similarityScore: 52,
    status: "high",
    aiFlagged: true,
    project: "Báo cáo môn học",
    wordCount: 1590,
  },
  {
    id: "hist-4",
    title: "Phân Tích Chuỗi Cung Ứng Nông Sản Việt Nam Trong Bối Cảnh Hội Nhập",
    date: "2026-05-30",
    similarityScore: 8,
    status: "clean",
    aiFlagged: false,
    project: "Nghiên cứu khoa học",
    wordCount: 3120,
  },
  {
    id: "hist-5",
    title: "Nghiên Cứu Về Hiệu Quả Học Tập Trực Tuyến Sau Đại Dịch COVID-19",
    date: "2026-05-12",
    similarityScore: 12,
    status: "low",
    aiFlagged: false,
    project: "Báo cáo môn học",
    wordCount: 2075,
  },
];
